### ISSUE TITLE
Not working with wpml 

### ISSUE THREAD

**Issue by jsuch11** [sukiwp/popup-trigger-url-for-elementor-pro#2]
Hi,
I used your plugin to set up a popup on a html link, however, when translating the page where I use it, it doesn't show me the popup in that other language.. It actually doesn't show me any popup. It would be great to have the url also for the other language. I use WPML to translate my site. 

Thanks again

**Comment by daviedR** [comment]
Hi @jsuch11 

Have you translated the popup as well? The trigger link for each language is different.

For example:
You have 2 languages in your WPML: English and French.
You have created the popup and the page where you put the trigger link in English.
After translating both popup and the page into French, you need to copy the trigger link of the French popup to your French page.

**Comment by jsuch11** [comment]
Hi @daviedR,
Thanks for the reply. I have indeed translated the popup, but I used WPML and so the French pop up for exemple doesn’t show the links. Based on what your suggesting me, I should duplicate the popup in English, and make it in French. This means they both appear as being in English(the default language) but they are not. 
Right ?

**Comment by daviedR** [comment]
So, after you created a popup in English, you could create the French version. So you would have 2 popups: 1 in English and 1 in French.

Since you are using WPML, you can switch between English and French language when on admin pages, right? There should be a language switcher in your admin toolbar.

So you can go to Templates > Popups. And copy the trigger URL for the particular language.
- First, let's say you are in English language mode.
- Copy the URL of the English popup to a link in your English page.
- Switch to French language.
- Copy the URL of the French popup to a link in your French page.

And don't forget to set the Display Conditions on both popups.

**Comment by jsuch11** [comment]
Hi @daviedR,
Thanks for tutorial, it worked perfectly !
Great support !
